services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    command: node index.js
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${BACKEND_PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    build: 
      context: ./server
      dockerfile: Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./server:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  frontend:
    command: npm run dev
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - VITE_API_TARGET=http://backend:${BACKEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./client:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    # networks:
    #   - front-tier
    #   - back-tier
    # configs:
    #   - httpd-config
    # secrets:
    #   - server-certificate

  
volumes:
  mongo-data:


# configs:
#   httpd-config:
#     external: true

# secrets:
#   server-certificate:
#     external: true

# networks:
#   # The presence of these objects is sufficient to define them
#   front-tier: {}
#   back-tier: {}